compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.5.3.cjs

packageExtensions:
  eslint-plugin-import-x@*:
    dependencies:
      "@typescript-eslint/parser": "^8.16.0"
