compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  eslint-plugin-import-x@*:
    dependencies:
      "@typescript-eslint/parser": ^8.16.0

yarnPath: .yarn/releases/yarn-4.6.0.cjs
