import { css } from "@emotion/react";
import { normalize } from "./normalize";

export const globalStyles = css`
  ${normalize}

  html, body {
    width: 100%;
  }

  body {
    font-family: "Merriweather", "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: #233343;
  }

  ul,
  p {
    font-size: 21px;
    font-weight: 300;
    line-height: 35px;
  }

  li {
    margin-bottom: 13px;
  }

  #quote {
  }

  h1,
  h2 {
    color: #000;
  }

  h1 {
    font-weight: bold;
    text-align: center;
    font-size: 45pt;
    margin-top: 72px;
    margin-bottom: 50px;
  }

  h2 {
    font-size: 20pt;
    font-weight: bold;
  }

  #bar {
    background-color: #3873a3;
    height: 10px;
    width: 100%;
  }

  a {
    color: #3271a7;
  }

  a:hover {
    color: #888;
  }

  h1.post {
    margin-bottom: 30px;
  }

  pre {
    text-align: left;
    font-size: 12pt;
  }

  @media only screen and (max-width: 767px) {
    h1 {
      text-align: left;
      font-size: 40px;
      margin: 35px 0 16px;
    }
    #quote {
      text-align: left;
      font-size: 14pt;
    }
    #post {
      text-align: left;
    }
  }

  /* Generated by pandoc. */
  table.sourceCode,
  tr.sourceCode,
  td.lineNumbers,
  td.sourceCode,
  table.sourceCode pre {
    margin: 0;
    padding: 0;
    border: 0;
    vertical-align: baseline;
    border: none;
  }
  td.lineNumbers {
    border-right: 1px solid #aaaaaa;
    text-align: right;
    color: #aaaaaa;
    padding-right: 5px;
    padding-left: 5px;
  }
  td.sourceCode {
    padding-left: 5px;
  }
  .sourceCode span.kw {
    color: #007020;
    font-weight: bold;
  }
  .sourceCode span.dt {
    color: #902000;
  }
  .sourceCode span.dv {
    color: #40a070;
  }
  .sourceCode span.bn {
    color: #40a070;
  }
  .sourceCode span.fl {
    color: #40a070;
  }
  .sourceCode span.ch {
    color: #4070a0;
  }
  .sourceCode span.st {
    color: #4070a0;
  }
  .sourceCode span.co {
    color: #60a0b0;
    font-style: italic;
  }
  .sourceCode span.ot {
    color: #007020;
  }
  .sourceCode span.al {
    color: red;
    font-weight: bold;
  }
  .sourceCode span.fu {
    color: #06287e;
  }
  .sourceCode span.re {
  }
  .sourceCode span.er {
    color: red;
    font-weight: bold;
  }

  pre {
    background-color: #f6f6f6;
    padding: 10px 20px;
    border-left: 4px solid #3873a3;
  }

  #thanks {
    margin: 3em auto;
    border-top: 1px solid #ddd;
    padding: 1em 0.5em;
    border-bottom: 1px solid #ddd;
  }

  #post blockquote {
    border-left: 2px solid #455565;
    font-style: italic;
    color: #666;
    margin: 10px 5px;
    padding: 5px 25px;
  }

  #post p > img {
    width: 100%;
    margin: 0 0 60px;
  }

  figure {
    width: 100%;
    margin: 60px auto;
  }

  figure img {
    max-width: 100%;
    display: block;
    margin: 0px auto;
  }

  figcaption {
    text-align: center;
    font-style: italic;
    color: #777;
  }
`;
