name: Lint

on: [push]

defaults:
  run:
    shell: nix develop --command bash {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn lint
      - run: yarn typecheck
