name: Lint

on: [push]

defaults:
  run:
    shell: nix develop --command bash {0}

jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn build:static

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: yarn typecheck
