name: Nix environment

on:
  push:
    branches:
      - master
    paths:
      - "*.nix"
      - flake.lock
  pull_request:
    branches:
      - master
    paths:
      - "*.nix"
      - flake.lock

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: igm
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check flake
        run: nix flake check -v --show-trace --no-update-lock-file
      - run: nix develop -c echo success
